### ISSUE TITLE
Error when getting image

### ISSUE THREAD

**Issue by simonfruehauf** [Patrick-Hogan/wandering_inn#14] opened 2023-04-01 07:16 UTC
When scraping Volume 7, this error happens regularly - sometimes in early chapters, sometimes in a bit later ones, but it never reaches 100%.

I believe this might be related to the new formats on the original website?

```
Traceback (most recent call last):
  File "C:\Users\User\wandering_inn\wanderinginn2epub.py", line 382, in <module>
    main()
  File "C:\Users\User\wandering_inn\wanderinginn2epub.py", line 363, in main
    get_book(volume_data,
  File "C:\Users\User\wandering_inn\wanderinginn2epub.py", line 304, in get_book
    ch.save(stream=fh, strip_color=strip_color, image_path=image_path)
  File "C:\Users\User\wandering_inn\wanderinginn2epub.py", line 124, in save
    with open(os.path.join(image_path, img_filename), 'wb') as fo:
OSError: [Errno 22] Invalid argument: './build\\html\\images\\hs_deceiver_final_lowres.jpg?fit=2908%2C2821&ssl=1'
```

**Comment by Patrick-Hogan** [comment] 2023-04-07 23:58
It might be fixed with the latest commit on master--I had errors downloading some images, so it should split all image urls on "?" when trying to determine a file name.

Unfortunately, I'm not able to test right now--I'm getting a 403 error when accessing anything on wanderinginn.com from my home IP, and navigating in browser shows: 

> WordPress Backup & Security Plugin - BlogVault Firewall
>
>Blocked because of Malicious Activities
>
>Reference ID: ############

Which makes me think the site firewall has been adjusted to prevent scraping, since I'm reasonably certain that's the only activity coming from my IP that would trip any firewall rules (rate limits on page access). I don't see any updated terms of service or request not to scrape the site when I check from my phone, but that may render this project pretty useless if others start to hit the same error.

**Comment by Patrick-Hogan** [comment] 2023-04-24 01:44
I found another instance that may have been the cause of the error you're seeing and pushed to [14-error-when-getting-image](https://github.com/Patrick-Hogan/wandering_inn/tree/14-error-when-getting-image). I'm banned again for now, so no real testing complete, but it might be helpful to you. 

I'm currently strongly considering dropping all images from the epub by default (option to add them in, but otherwise replace with image alt text or title). They aren't usually part of the chapter and wouldn't display well on most e-ink displays anyways, so it doesn't seem worth the hassle to keep them.

**Comment by Patrick-Hogan** [comment] 2024-01-08 05:47
I think this is fixed, now--at an rate, I was able to download new chapters w/ images successfully. Closing for now, but please re-open if you continue to see it (may need to do more robust client-side checks for local image validity).

**Closed as completed by Patrick-Hogan** 2024-01-08 05:47 UTC
